### ISSUE TITLE
customizable shortcut

### ISSUE THREAD

**Issue by fouad** [fouad/chrome-tablight#1]
Support user-defined shortcuts to open search.

Problems websites (try using shortcut):
[Google docs](https://docs.google.com/document/d/1XXMvReO8-Awi1EZXAXS4PzDzdNvV6pGcuaF4Q9821Es/edit)

**Comment by tiye** [comment]
I installed this in Chrome but failed to trigger it in OS X..
Is it just like mine: https://github.com/jiyinyiyong/tab-searching

**Comment by Arduinology** [comment]
I install this in Chromium on Ubuntu 14.01 but the shortcut fails to work.

**Comment by bendem** [comment]
The shortcut <kbd>CTRL</kbd> + <kbd>O</kbd> doesn't do anything on `Google Chrome Version 40.0.2214.45 beta-m (64-bit)` (Windows 8) either.

**Comment by fouad** [comment]
A few issues here, I had keystroke listeners in `contentscript.js`, which meant 1) tabs had to be refreshed after install 2) hard-coded shortcuts.

I moved to chrome keyboard shortcuts defined in `manifest.json` which allow users to update [extension shortcuts](chrome://extensions/configureCommands).

**Comment by bendem** [comment]
Awesome, thanks!
