### ISSUE TITLE
Reduce Permissions

### ISSUE THREAD

**Issue by niedzielski** [fouad/chrome-tablight#4]
This is an enhancement request to reduce the permission requirements. When installing, Chrome ominously warns, "read and change all your data on the websites you visit."

**Comment by Arduinology** [comment]
+1 What sort of manipulation / data reading is going on?

**Comment by fouad** [comment]
Sorry for the confusion here! This will be for #5 where you can trigger actions on pages through the search bar (like search a song on SoundCloud or Google Play Music)
